# SVD of Rank Deficient Matrix

In [1]:
import numpy as np

In [32]:
M = np.array([[1,0,3],
    [3,7,2],
    [2,-2,8],
    [0,-1,1],
    [5,8,7],
    ])
M

array([[ 1,  0,  3],
       [ 3,  7,  2],
       [ 2, -2,  8],
       [ 0, -1,  1],
       [ 5,  8,  7]])

In [33]:
A = M.T @ M
A

array([[ 39,  57,  60],
       [ 57, 118,  53],
       [ 60,  53, 127]])

In [34]:
B = M @ M.T
B

array([[ 10,   9,  26,   3,  26],
       [  9,  62,   8,  -5,  85],
       [ 26,   8,  72,  10,  50],
       [  3,  -5,  10,   2,  -1],
       [ 26,  85,  50,  -1, 138]])

## Eigenvalues

In [35]:
eigvals, eigvecs = np.linalg.eig(A)
eigvals, eigvecs

(array([ 2.14670489e+02, -1.50990331e-14,  6.93295108e+01]),
 array([[ 0.42615127,  0.90453403, -0.01460404],
        [ 0.61500884, -0.30151134, -0.72859799],
        [ 0.66344497, -0.30151134,  0.68478587]]))

In [36]:
eigvals, eigvecs = np.linalg.eig(B)
eigvals, eigvecs

(array([ 2.14670489e+02, -5.99520433e-15,  6.93295108e+01,  1.23720729e-14,
        -7.24621456e-16]),
 array([[-0.16492942, -0.95539856,  0.24497323, -0.06464508, -0.10671808],
        [-0.47164732, -0.03481209, -0.45330644,  0.75010839, -0.04684757],
        [-0.33647055,  0.27076072,  0.82943965,  0.3284142 , -0.17364364],
        [-0.00330585,  0.04409532,  0.16974659,  0.04591676,  0.97063121],
        [-0.79820031,  0.10366268, -0.13310656, -0.5685017 ,  0.11890961]]))

## SVD

In [59]:
eigvals, eigvecs = np.linalg.eig(A)
V = eigvecs[:, (0,2)]
eigvals, eigvecs = np.linalg.eig(B)
U = eigvecs[:, (0,2)]
M = U @ np.array([[-np.sqrt(2.14670489e+02), 0],[0,-np.sqrt(6.93295108e+01)]]) @ V.T
M

array([[ 1.05957729,  2.97232071,  0.20641116],
       [ 2.88975624,  1.4999211 ,  7.16934763],
       [ 2.20171904,  8.063796  , -1.45863887],
       [ 0.04128223,  1.05957729, -0.93573059],
       [ 4.96762859,  6.38498522,  8.51790055]])

## 1-D Approximation

In [58]:
V = V[:,0:1]
U = U[:,0:1]
N = U @ np.array([[-np.sqrt(2.14670489e+02)]]) @ V.T
N

array([[1.02978864, 1.48616035, 1.60320558],
       [2.94487812, 4.24996055, 4.58467382],
       [2.10085952, 3.031898  , 3.27068057],
       [0.02064112, 0.02978864, 0.0321347 ],
       [4.98381429, 7.19249261, 7.75895027]])

In [61]:
eigvals, eigvecs = np.linalg.eig(A)
V = eigvecs[:, (0,2)]
eigvals, eigvecs = np.linalg.eig(B)
U = eigvecs[:, (0,2)]
M = U @ np.array([[-np.sqrt(2.14670489e+02), 0],[0,0]]) @ V.T
M

array([[1.02978864, 1.48616035, 1.60320558],
       [2.94487812, 4.24996055, 4.58467382],
       [2.10085952, 3.031898  , 3.27068057],
       [0.02064112, 0.02978864, 0.0321347 ],
       [4.98381429, 7.19249261, 7.75895027]])